spring:
  datasource:
    url: jdbc:postgresql://db:5432/database  # ✅ Changed to service name "db"
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

server:
  address: 0.0.0.0
  port: 8080

application:
  security:
    jwt:
      secret-key: c2VjcmV0S2V5MjAyNS0xMjMtYXNkZjEyMzEyMyE=
      expiration: 86400000
      refresh-token:
        expiration: 604800000

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG