spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DarkWeb
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080