spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DarkWeb
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: c2VjcmV0S2V5MjAyNS0xMjMtYXNkZjEyMzEyMyE=
      expiration: 86400000
      refresh-token:
        expiration: 604800000