spring:
  datasource:
    url: jdbc:postgresql://db:5432/DarkWeb  # Use 'db' as hostname for Docker
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # Change to 'validate' or 'none' in production
    show-sql: true

  sql:
    init:
      mode: always  # Change to 'never' if you don't want to initialize scripts

server:
  address: 0.0.0.0
  port: 8080

application:
  security:
    jwt:
      secret-key: c2VjcmV0S2V5MjAyNS0xMjMtYXNkZjEyMzEyMyE=  # Example Base64 key
      expiration: 86400000  # 1 day in milliseconds
      refresh-token:
        expiration: 604800000  # 7 days in milliseconds

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG