spring:
  datasource:
    url: ${DATABASE_URL}  # Use the environment variable provided by Fly.io
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # Change to 'validate' or 'none' in production
    show-sql: true

  sql:
    init:
      mode: always  # Change to 'never' if you don't want to initialize scripts

server:
  port: 8080
  address: 0.0.0.0  # Ensure app listens on all interfaces


application:
  security:
    jwt:
      secret-key: c2VjcmV0S2V5MjAyNS0xMjMtYXNkZjEyMzEyMyE=  # Example Base64 key
      expiration: 86400000  # 1 day in milliseconds
      refresh-token:
        expiration: 604800000  # 7 days in milliseconds

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
